# Generated by Django 4.2 on 2025-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=15)),
                ('address', models.BigIntegerField()),
                ('balance', models.FloatField()),
            ],
        ),
    ]
