# Generated by Django 4.2 on 2025-02-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
