# Generated by Django 4.2 on 2025-03-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_country_code_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
