# Generated by Django 4.2 on 2025-02-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_address_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=15)),
                ('province', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
