# Generated by Django 4.2 on 2025-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("destination", models.JSONField()),
                ("description", models.TextField()),
                ("commission", models.FloatField(blank=True, default=0, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Awaiting Acceptance"),
                            (1, "Order Accepted"),
                            (2, "Completed"),
                            (3, "Cancelled"),
                        ],
                        default=0,
                    ),
                ),
                ("images", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
