# Generated by Django 4.2 on 2025-03-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Awaiting Acceptance"),
                    (1, "Order Accepted"),
                    (2, "Completed"),
                    (3, "Cancelled"),
                ],
                default=0,
            ),
        ),
    ]
